works:
  - canonical: "Comentários à Constituição Brasileira de 1988"
    variants:
      - "Comentários à Constituição do Brasil: promulgada em 5 de outubro de 1988"
      - "Comentários à Constituição Federal Brasileira"
